spring.application.name=progetto_finale_aliceaccillaro

spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleAliceAccillaro
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# SUPABASE
supabase.url=https://ysicdtcanbjhckmdzoxu.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzaWNkdGNhbmJqaGNrbWR6b3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwODcwNjUsImV4cCI6MjEwNTY2MzA2NX0.pZjvRyifaG5TneNZ6YQzRXTHRSlRqf2GqHWa97giYDg
supabase.bucket=/storage/v1/object/images/
supabase.image=/storage/v1/object/public/images/

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=00f6b9d62be13c
spring.mail.password=ec86a1a7190f3d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
